// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
)

// Defines values for ErrorCode.
const (
	ErrorCodeDuplicateSku     ErrorCode = "duplicate_sku"
	ErrorCodeNotFound         ErrorCode = "not_found"
	ErrorCodePermissionDenied ErrorCode = "permission_denied"
	ErrorCodeRateLimited      ErrorCode = "rate_limited"
	ErrorCodeValidationFailed ErrorCode = "validation_failed"
	ErrorCodeVersionConflict  ErrorCode = "version_conflict"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeDuplicateSku:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodePermissionDenied:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeValidationFailed:
		return true
	case ErrorCodeVersionConflict:
		return true
	default:
		return false
	}
}

// ErrorCode The canonical error codes for this phase. The code also appears as the last segment of a
// `Problem.type` URI, and directly in per-row results where an operation partially succeeds
// — see `API spec.md` §6.2.
type ErrorCode string

// Money An integer amount in **minor units** plus an ISO 4217 currency. `2000000` + `IDR` is
// Rp 20.000.
//
// Never a float and never a decimal string. IDR has no minor unit in practice, but the
// scale of 2 is kept uniform so multi-currency is not a migration.
type Money struct {
	// Amount Examples: 19900000
	Amount int64 `json:"amount"`

	// Currency Examples: IDR
	Currency string `json:"currency"`
}

// Problem RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type Problem struct {
	// Detail Examples: Product was modified by another user. Reload and retry.
	Detail *string         `json:"detail,omitempty"`
	Errors *[]ProblemError `json:"errors,omitempty"`

	// Instance Examples: /v1/products/01926f3a-0000-7000-8000-000000000000
	Instance *string `json:"instance,omitempty"`

	// Status Examples: 409
	Status int `json:"status"`

	// Title Examples: Version conflict
	Title string `json:"title"`

	// TraceId Examples: 4bf92f3577b34da6a3ce929d0e0e4736
	TraceId string `json:"trace_id"`

	// Type Examples: https://docs.example.com/errors/version-conflict
	Type string `json:"type"`
}

// ProblemError One field-level detail inside a `Problem`. Carries whatever the specific failure needs —
// a version conflict reports `expected` and `supplied`, a validation failure reports a
// message — so extra properties are permitted by design.
type ProblemError struct {
	Detail *string `json:"detail,omitempty"`

	// Field Examples: version
	Field                string                 `json:"field"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Cursor defines model for Cursor.
type Cursor = string

// IfMatch defines model for IfMatch.
type IfMatch = int

// Limit defines model for Limit.
type Limit = int

// BadRequest RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type BadRequest = Problem

// Conflict RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type Conflict = Problem

// Forbidden RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type Forbidden = Problem

// NotFound RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type NotFound = Problem

// TooManyRequests RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type TooManyRequests = Problem

// Unauthorized RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type Unauthorized = Problem

// UnprocessableEntity RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type UnprocessableEntity = Problem

// Getter for additional properties for ProblemError. Returns the specified
// element and whether it was found
func (a ProblemError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemError
func (a *ProblemError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemError to handle AdditionalProperties
func (a *ProblemError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemError to handle AdditionalProperties
func (a ProblemError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	object["field"], err = json.Marshal(a.Field)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'field': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RateLimitLimit     *int
	RateLimitRemaining *int
	RateLimitReset     *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type UnprocessableEntityApplicationProblemPlusJSONResponse Problem

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}
