// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CategoryKind.
const (
	CategoryKindActivity   CategoryKind = "activity"
	CategoryKindCategory   CategoryKind = "category"
	CategoryKindCollection CategoryKind = "collection"
	CategoryKindCustom     CategoryKind = "custom"
	CategoryKindSeries     CategoryKind = "series"
)

// Valid indicates whether the value is a known member of the CategoryKind enum.
func (e CategoryKind) Valid() bool {
	switch e {
	case CategoryKindActivity:
		return true
	case CategoryKindCategory:
		return true
	case CategoryKindCollection:
		return true
	case CategoryKindCustom:
		return true
	case CategoryKindSeries:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeCategoryInUse            ErrorCode = "category_in_use"
	ErrorCodeChannelUnavailable       ErrorCode = "channel_unavailable"
	ErrorCodeCustomerAuthRequired     ErrorCode = "customer_auth_required"
	ErrorCodeDuplicateSku             ErrorCode = "duplicate_sku"
	ErrorCodeEmptyCart                ErrorCode = "empty_cart"
	ErrorCodeIllegalTransition        ErrorCode = "illegal_transition"
	ErrorCodeInternal                 ErrorCode = "internal"
	ErrorCodeInvalidApiKey            ErrorCode = "invalid_api_key"
	ErrorCodeItemUnavailable          ErrorCode = "item_unavailable"
	ErrorCodeNotFound                 ErrorCode = "not_found"
	ErrorCodeOriginNotAllowed         ErrorCode = "origin_not_allowed"
	ErrorCodePaymentUnavailable       ErrorCode = "payment_unavailable"
	ErrorCodePermissionDenied         ErrorCode = "permission_denied"
	ErrorCodePublishCheckFailed       ErrorCode = "publish_check_failed"
	ErrorCodeRateLimited              ErrorCode = "rate_limited"
	ErrorCodeShippingRatesUnavailable ErrorCode = "shipping_rates_unavailable"
	ErrorCodeShippingUnavailable      ErrorCode = "shipping_unavailable"
	ErrorCodeUnauthenticated          ErrorCode = "unauthenticated"
	ErrorCodeUnknownField             ErrorCode = "unknown_field"
	ErrorCodeValidationFailed         ErrorCode = "validation_failed"
	ErrorCodeVersionConflict          ErrorCode = "version_conflict"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeCategoryInUse:
		return true
	case ErrorCodeChannelUnavailable:
		return true
	case ErrorCodeCustomerAuthRequired:
		return true
	case ErrorCodeDuplicateSku:
		return true
	case ErrorCodeEmptyCart:
		return true
	case ErrorCodeIllegalTransition:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidApiKey:
		return true
	case ErrorCodeItemUnavailable:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeOriginNotAllowed:
		return true
	case ErrorCodePaymentUnavailable:
		return true
	case ErrorCodePermissionDenied:
		return true
	case ErrorCodePublishCheckFailed:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeShippingRatesUnavailable:
		return true
	case ErrorCodeShippingUnavailable:
		return true
	case ErrorCodeUnauthenticated:
		return true
	case ErrorCodeUnknownField:
		return true
	case ErrorCodeValidationFailed:
		return true
	case ErrorCodeVersionConflict:
		return true
	default:
		return false
	}
}

// Defines values for RoleName.
const (
	RoleNameAdmin  RoleName = "admin"
	RoleNameOps    RoleName = "ops"
	RoleNameOwner  RoleName = "owner"
	RoleNameViewer RoleName = "viewer"
)

// Valid indicates whether the value is a known member of the RoleName enum.
func (e RoleName) Valid() bool {
	switch e {
	case RoleNameAdmin:
		return true
	case RoleNameOps:
		return true
	case RoleNameOwner:
		return true
	case RoleNameViewer:
		return true
	default:
		return false
	}
}

// Defines values for SessionUserRole.
const (
	SessionUserRoleAdmin  SessionUserRole = "admin"
	SessionUserRoleOps    SessionUserRole = "ops"
	SessionUserRoleOwner  SessionUserRole = "owner"
	SessionUserRoleViewer SessionUserRole = "viewer"
)

// Valid indicates whether the value is a known member of the SessionUserRole enum.
func (e SessionUserRole) Valid() bool {
	switch e {
	case SessionUserRoleAdmin:
		return true
	case SessionUserRoleOps:
		return true
	case SessionUserRoleOwner:
		return true
	case SessionUserRoleViewer:
		return true
	default:
		return false
	}
}

// Brand defines model for Brand.
type Brand struct {
	ArchivedAt *time.Time         `json:"archived_at"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`

	// Slug Derived from `name`; read-only (BR-030).
	//
	// Examples: erigo
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updated_at"`
}

// BrandPage defines model for BrandPage.
type BrandPage struct {
	Data       []Brand `json:"data"`
	NextCursor *string `json:"next_cursor"`
}

// BrandWrite defines model for BrandWrite.
type BrandWrite struct {
	Name string `json:"name"`
}

// Category defines model for Category.
type Category struct {
	ArchivedAt *time.Time         `json:"archived_at"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`

	// Kind Independent trees; a product may sit in several (BR-031).
	Kind     CategoryKind        `json:"kind"`
	Name     string              `json:"name"`
	ParentId *openapi_types.UUID `json:"parent_id"`

	// Path Derived by the database from names and parents; read-only (BR-032).
	//
	// Examples: apparel.outerwear.jackets
	Path      string    `json:"path"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CategoryCreate defines model for CategoryCreate.
type CategoryCreate struct {
	// Kind Independent trees; a product may sit in several (BR-031).
	Kind     *CategoryKind       `json:"kind,omitempty"`
	Name     string              `json:"name"`
	ParentId *openapi_types.UUID `json:"parent_id,omitempty"`
}

// CategoryDetail defines model for CategoryDetail.
type CategoryDetail struct {
	ArchivedAt      *time.Time         `json:"archived_at"`
	CreatedAt       time.Time          `json:"created_at"`
	DescendantCount int                `json:"descendant_count"`
	Id              openapi_types.UUID `json:"id"`

	// Kind Independent trees; a product may sit in several (BR-031).
	Kind     CategoryKind        `json:"kind"`
	Name     string              `json:"name"`
	ParentId *openapi_types.UUID `json:"parent_id"`

	// Path Derived by the database from names and parents; read-only (BR-032).
	//
	// Examples: apparel.outerwear.jackets
	Path         string    `json:"path"`
	ProductCount int       `json:"product_count"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// CategoryKind Independent trees; a product may sit in several (BR-031).
type CategoryKind string

// CategoryList defines model for CategoryList.
type CategoryList struct {
	Data []Category `json:"data"`
}

// CategoryUpdate defines model for CategoryUpdate.
type CategoryUpdate struct {
	Name     *string             `json:"name,omitempty"`
	ParentId *openapi_types.UUID `json:"parent_id,omitempty"`
}

// ErrorCode The canonical error codes, listed with their status and rule in `04-api-spec.md` §1.1.
// The code also appears as the last segment of a `Problem.type` URI, and directly in
// per-row results where an operation partially succeeds (§7.3, §7.5).
type ErrorCode string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email Examples: ops@erigo.co.id
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Money An amount in **minor units**, always IDR: `2000000` is Rp 20.000. A plain integer, never
// a float, a decimal string or an object; there is no currency field because there is only
// one currency (BR-006, BR-029). Clients divide by 100 to display.
//
// Examples: 19900000
type Money = int64

// Problem RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type Problem struct {
	// Detail Examples: Product was modified by another user. Reload and retry.
	Detail *string         `json:"detail,omitempty"`
	Errors *[]ProblemError `json:"errors,omitempty"`

	// Instance Examples: /v1/products/01926f3a-0000-7000-8000-000000000000
	Instance *string `json:"instance,omitempty"`

	// Status Examples: 409
	Status int `json:"status"`

	// Title Examples: Version conflict
	Title string `json:"title"`

	// TraceId Examples: 4bf92f3577b34da6a3ce929d0e0e4736
	TraceId string `json:"trace_id"`

	// Type Examples: https://docs.example.com/errors/version_conflict
	Type string `json:"type"`
}

// ProblemError One field-level detail inside a `Problem`. Carries whatever the specific failure needs —
// a version conflict reports `expected` and `supplied`, a validation failure reports a
// message — so extra properties are permitted by design.
type ProblemError struct {
	Detail *string `json:"detail,omitempty"`

	// Field Examples: version
	Field                string                 `json:"field"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Role One of the four seeded roles and everything it grants.
type Role struct {
	// Description One line a client can show next to the role in a picker.
	Description *string  `json:"description,omitempty"`
	Name        RoleName `json:"name"`
	Permissions []string `json:"permissions"`
}

// RoleName defines model for Role.Name.
type RoleName string

// Session Returned by both login and refresh. Carries everything the client needs to render a
// signed-in shell without a second request.
//
// The refresh token is **not** here -- it is in an httpOnly cookie, out of reach of any
// script on the page.
type Session struct {
	// AccessToken JWT. Held in memory only, never in localStorage.
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds until the access token expires.
	//
	// Examples: 900
	ExpiresIn int           `json:"expires_in"`
	Tenant    SessionTenant `json:"tenant"`
	User      SessionUser   `json:"user"`
}

// SessionTenant defines model for SessionTenant.
type SessionTenant struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`

	// Timezone IANA name. Display only; the wire is always WIB, `+07:00` (BR-007).
	//
	// Examples: Asia/Jakarta
	Timezone string `json:"timezone"`
}

// SessionUser defines model for SessionUser.
type SessionUser struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`

	// Permissions `resource:action` strings the role grants. The client hides actions it does not find
	// here rather than disabling them -- a button that 403s advertises a capability the user
	// does not have.
	Permissions []string        `json:"permissions"`
	Role        SessionUserRole `json:"role"`
}

// SessionUserRole defines model for SessionUser.Role.
type SessionUserRole string

// Cursor defines model for Cursor.
type Cursor = string

// Id defines model for Id.
type Id = openapi_types.UUID

// IfMatch defines model for IfMatch.
type IfMatch = int

// Limit defines model for Limit.
type Limit = int

// BadRequest RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type BadRequest = Problem

// Conflict RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type Conflict = Problem

// Forbidden RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type Forbidden = Problem

// NotFound RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type NotFound = Problem

// TooManyRequests RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type TooManyRequests = Problem

// Unauthorized RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type Unauthorized = Problem

// UnprocessableEntity RFC 9457 `application/problem+json`. Every error response in this API uses it.
//
// `trace_id` is the OpenTelemetry trace id — a support ticket quoting it goes straight to
// the span. There is no separate `code` field: the code is the last segment of `type`.
type UnprocessableEntity = Problem

// ListBrandsParams defines parameters for ListBrands.
type ListBrandsParams struct {
	Q        *string `form:"q,omitempty" json:"q,omitempty"`
	Archived *bool   `form:"archived,omitempty" json:"archived,omitempty"`

	// Limit Page size. Pairs with `cursor`; there is no `offset` in this API.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor from the previous page. Cursor pagination only — a deep `offset` on a large
	// table is a sequential scan, so the parameter does not exist.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListCategoriesParams defines parameters for ListCategories.
type ListCategoriesParams struct {
	Kind     *CategoryKind       `form:"kind,omitempty" json:"kind,omitempty"`
	ParentId *openapi_types.UUID `form:"parent_id,omitempty" json:"parent_id,omitempty"`
	Depth    *int                `form:"depth,omitempty" json:"depth,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateBrandJSONRequestBody defines body for CreateBrand for application/json ContentType.
type CreateBrandJSONRequestBody = BrandWrite

// UpdateBrandJSONRequestBody defines body for UpdateBrand for application/json ContentType.
type UpdateBrandJSONRequestBody = BrandWrite

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CategoryCreate

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = CategoryUpdate

// Getter for additional properties for ProblemError. Returns the specified
// element and whether it was found
func (a ProblemError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemError
func (a *ProblemError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemError to handle AdditionalProperties
func (a *ProblemError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemError to handle AdditionalProperties
func (a ProblemError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	object["field"], err = json.Marshal(a.Field)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'field': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Exchange an email and password for an access token
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Revoke the current refresh token
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Refresh Rotate the refresh token and issue a new access token
	// (POST /auth/refresh)
	Refresh(w http.ResponseWriter, r *http.Request)
	// ListBrands Brands, sorted by name
	// (GET /brands)
	ListBrands(w http.ResponseWriter, r *http.Request, params ListBrandsParams)
	// CreateBrand Create a brand
	// (POST /brands)
	CreateBrand(w http.ResponseWriter, r *http.Request)
	// ArchiveBrand Archive a brand
	// (DELETE /brands/{id})
	ArchiveBrand(w http.ResponseWriter, r *http.Request, id Id)
	// GetBrand One brand
	// (GET /brands/{id})
	GetBrand(w http.ResponseWriter, r *http.Request, id Id)
	// UpdateBrand Rename a brand
	// (PATCH /brands/{id})
	UpdateBrand(w http.ResponseWriter, r *http.Request, id Id)
	// ListCategories Categories, flat, sorted by kind then path
	// (GET /categories)
	ListCategories(w http.ResponseWriter, r *http.Request, params ListCategoriesParams)
	// CreateCategory Create a category
	// (POST /categories)
	CreateCategory(w http.ResponseWriter, r *http.Request)
	// ArchiveCategory Archive a category
	// (DELETE /categories/{id})
	ArchiveCategory(w http.ResponseWriter, r *http.Request, id Id)
	// GetCategory One category, with the counts the move dialog needs
	// (GET /categories/{id})
	GetCategory(w http.ResponseWriter, r *http.Request, id Id)
	// UpdateCategory Rename or move a category
	// (PATCH /categories/{id})
	UpdateCategory(w http.ResponseWriter, r *http.Request, id Id)
	// ListRoles The four seeded roles and the permissions each grants
	// (GET /roles)
	ListRoles(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login Exchange an email and password for an access token
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Revoke the current refresh token
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh Rotate the refresh token and issue a new access token
// (POST /auth/refresh)
func (_ Unimplemented) Refresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListBrands Brands, sorted by name
// (GET /brands)
func (_ Unimplemented) ListBrands(w http.ResponseWriter, r *http.Request, params ListBrandsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateBrand Create a brand
// (POST /brands)
func (_ Unimplemented) CreateBrand(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ArchiveBrand Archive a brand
// (DELETE /brands/{id})
func (_ Unimplemented) ArchiveBrand(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetBrand One brand
// (GET /brands/{id})
func (_ Unimplemented) GetBrand(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateBrand Rename a brand
// (PATCH /brands/{id})
func (_ Unimplemented) UpdateBrand(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListCategories Categories, flat, sorted by kind then path
// (GET /categories)
func (_ Unimplemented) ListCategories(w http.ResponseWriter, r *http.Request, params ListCategoriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateCategory Create a category
// (POST /categories)
func (_ Unimplemented) CreateCategory(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ArchiveCategory Archive a category
// (DELETE /categories/{id})
func (_ Unimplemented) ArchiveCategory(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCategory One category, with the counts the move dialog needs
// (GET /categories/{id})
func (_ Unimplemented) GetCategory(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateCategory Rename or move a category
// (PATCH /categories/{id})
func (_ Unimplemented) UpdateCategory(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListRoles The four seeded roles and the permissions each grants
// (GET /roles)
func (_ Unimplemented) ListRoles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Refresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBrands operation middleware
func (siw *ServerInterfaceWrapper) ListBrands(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBrandsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "archived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "archived", r.URL.Query(), &params.Archived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "archived"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "archived", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBrands(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBrand operation middleware
func (siw *ServerInterfaceWrapper) CreateBrand(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBrand(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveBrand operation middleware
func (siw *ServerInterfaceWrapper) ArchiveBrand(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveBrand(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBrand operation middleware
func (siw *ServerInterfaceWrapper) GetBrand(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBrand(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateBrand operation middleware
func (siw *ServerInterfaceWrapper) UpdateBrand(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateBrand(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCategoriesParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", r.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "kind"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "parent_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "parent_id", r.URL.Query(), &params.ParentId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "parent_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parent_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "depth" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "depth", r.URL.Query(), &params.Depth, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "depth"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "depth", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCategories(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCategory operation middleware
func (siw *ServerInterfaceWrapper) CreateCategory(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCategory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveCategory operation middleware
func (siw *ServerInterfaceWrapper) ArchiveCategory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveCategory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCategory operation middleware
func (siw *ServerInterfaceWrapper) GetCategory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCategory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCategory operation middleware
func (siw *ServerInterfaceWrapper) UpdateCategory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCategory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRoles operation middleware
func (siw *ServerInterfaceWrapper) ListRoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/roles", wrapper.ListRoles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/brands", wrapper.ListBrands)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/brands", wrapper.CreateBrand)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/brands/{id}", wrapper.ArchiveBrand)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/brands/{id}", wrapper.GetBrand)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/brands/{id}", wrapper.UpdateBrand)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/categories", wrapper.ListCategories)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/categories", wrapper.CreateCategory)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/categories/{id}", wrapper.ArchiveCategory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/categories/{id}", wrapper.GetCategory)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/categories/{id}", wrapper.UpdateCategory)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RateLimitLimit     *int
	RateLimitRemaining *int
	RateLimitReset     *int
	RetryAfter         *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type UnprocessableEntityApplicationProblemPlusJSONResponse Problem

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie *string
}

type Login200JSONResponse struct {
	Body    Session
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response Login422ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type Login429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response Login429ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RateLimitLimit != nil {
		w.Header().Set("RateLimit-Limit", fmt.Sprint(*response.Headers.RateLimitLimit))
	}
	if response.Headers.RateLimitRemaining != nil {
		w.Header().Set("RateLimit-Remaining", fmt.Sprint(*response.Headers.RateLimitRemaining))
	}
	if response.Headers.RateLimitReset != nil {
		w.Header().Set("RateLimit-Reset", fmt.Sprint(*response.Headers.RateLimitReset))
	}
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie *string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type Logout401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Logout401ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshRequestObject struct {
}

type RefreshResponseObject interface {
	VisitRefreshResponse(w http.ResponseWriter) error
}

type Refresh200ResponseHeaders struct {
	SetCookie *string
}

type Refresh200JSONResponse struct {
	Body    Session
	Headers Refresh200ResponseHeaders
}

func (response Refresh200JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Refresh401ApplicationProblemPlusJSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListBrandsRequestObject struct {
	Params ListBrandsParams
}

type ListBrandsResponseObject interface {
	VisitListBrandsResponse(w http.ResponseWriter) error
}

type ListBrands200JSONResponse BrandPage

func (response ListBrands200JSONResponse) VisitListBrandsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListBrands401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListBrands401ApplicationProblemPlusJSONResponse) VisitListBrandsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListBrands403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListBrands403ApplicationProblemPlusJSONResponse) VisitListBrandsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListBrands422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response ListBrands422ApplicationProblemPlusJSONResponse) VisitListBrandsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBrandRequestObject struct {
	Body *CreateBrandJSONRequestBody
}

type CreateBrandResponseObject interface {
	VisitCreateBrandResponse(w http.ResponseWriter) error
}

type CreateBrand201JSONResponse Brand

func (response CreateBrand201JSONResponse) VisitCreateBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBrand401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateBrand401ApplicationProblemPlusJSONResponse) VisitCreateBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBrand403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response CreateBrand403ApplicationProblemPlusJSONResponse) VisitCreateBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBrand422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response CreateBrand422ApplicationProblemPlusJSONResponse) VisitCreateBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ArchiveBrandRequestObject struct {
	Id Id `json:"id"`
}

type ArchiveBrandResponseObject interface {
	VisitArchiveBrandResponse(w http.ResponseWriter) error
}

type ArchiveBrand204Response struct {
}

func (response ArchiveBrand204Response) VisitArchiveBrandResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ArchiveBrand401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ArchiveBrand401ApplicationProblemPlusJSONResponse) VisitArchiveBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ArchiveBrand403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ArchiveBrand403ApplicationProblemPlusJSONResponse) VisitArchiveBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ArchiveBrand404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ArchiveBrand404ApplicationProblemPlusJSONResponse) VisitArchiveBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetBrandRequestObject struct {
	Id Id `json:"id"`
}

type GetBrandResponseObject interface {
	VisitGetBrandResponse(w http.ResponseWriter) error
}

type GetBrand200JSONResponse Brand

func (response GetBrand200JSONResponse) VisitGetBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBrand401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetBrand401ApplicationProblemPlusJSONResponse) VisitGetBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetBrand403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetBrand403ApplicationProblemPlusJSONResponse) VisitGetBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetBrand404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetBrand404ApplicationProblemPlusJSONResponse) VisitGetBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateBrandRequestObject struct {
	Id   Id `json:"id"`
	Body *UpdateBrandJSONRequestBody
}

type UpdateBrandResponseObject interface {
	VisitUpdateBrandResponse(w http.ResponseWriter) error
}

type UpdateBrand200JSONResponse Brand

func (response UpdateBrand200JSONResponse) VisitUpdateBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateBrand401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UpdateBrand401ApplicationProblemPlusJSONResponse) VisitUpdateBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateBrand403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response UpdateBrand403ApplicationProblemPlusJSONResponse) VisitUpdateBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateBrand404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UpdateBrand404ApplicationProblemPlusJSONResponse) VisitUpdateBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateBrand422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response UpdateBrand422ApplicationProblemPlusJSONResponse) VisitUpdateBrandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ListCategoriesRequestObject struct {
	Params ListCategoriesParams
}

type ListCategoriesResponseObject interface {
	VisitListCategoriesResponse(w http.ResponseWriter) error
}

type ListCategories200JSONResponse CategoryList

func (response ListCategories200JSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCategories401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListCategories401ApplicationProblemPlusJSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListCategories403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListCategories403ApplicationProblemPlusJSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListCategories422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response ListCategories422ApplicationProblemPlusJSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCategoryRequestObject struct {
	Body *CreateCategoryJSONRequestBody
}

type CreateCategoryResponseObject interface {
	VisitCreateCategoryResponse(w http.ResponseWriter) error
}

type CreateCategory201JSONResponse Category

func (response CreateCategory201JSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCategory401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateCategory401ApplicationProblemPlusJSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCategory403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response CreateCategory403ApplicationProblemPlusJSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCategory422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response CreateCategory422ApplicationProblemPlusJSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ArchiveCategoryRequestObject struct {
	Id Id `json:"id"`
}

type ArchiveCategoryResponseObject interface {
	VisitArchiveCategoryResponse(w http.ResponseWriter) error
}

type ArchiveCategory204Response struct {
}

func (response ArchiveCategory204Response) VisitArchiveCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ArchiveCategory401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ArchiveCategory401ApplicationProblemPlusJSONResponse) VisitArchiveCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ArchiveCategory403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ArchiveCategory403ApplicationProblemPlusJSONResponse) VisitArchiveCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ArchiveCategory404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ArchiveCategory404ApplicationProblemPlusJSONResponse) VisitArchiveCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ArchiveCategory409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response ArchiveCategory409ApplicationProblemPlusJSONResponse) VisitArchiveCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetCategoryRequestObject struct {
	Id Id `json:"id"`
}

type GetCategoryResponseObject interface {
	VisitGetCategoryResponse(w http.ResponseWriter) error
}

type GetCategory200JSONResponse CategoryDetail

func (response GetCategory200JSONResponse) VisitGetCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCategory401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetCategory401ApplicationProblemPlusJSONResponse) VisitGetCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCategory403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetCategory403ApplicationProblemPlusJSONResponse) VisitGetCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetCategory404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetCategory404ApplicationProblemPlusJSONResponse) VisitGetCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCategoryRequestObject struct {
	Id   Id `json:"id"`
	Body *UpdateCategoryJSONRequestBody
}

type UpdateCategoryResponseObject interface {
	VisitUpdateCategoryResponse(w http.ResponseWriter) error
}

type UpdateCategory200JSONResponse Category

func (response UpdateCategory200JSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCategory401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UpdateCategory401ApplicationProblemPlusJSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCategory403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response UpdateCategory403ApplicationProblemPlusJSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCategory404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UpdateCategory404ApplicationProblemPlusJSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCategory422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response UpdateCategory422ApplicationProblemPlusJSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ListRolesRequestObject struct {
}

type ListRolesResponseObject interface {
	VisitListRolesResponse(w http.ResponseWriter) error
}

type ListRoles200JSONResponse []Role

func (response ListRoles200JSONResponse) VisitListRolesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoles401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListRoles401ApplicationProblemPlusJSONResponse) VisitListRolesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListRoles403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListRoles403ApplicationProblemPlusJSONResponse) VisitListRolesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login Exchange an email and password for an access token
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Revoke the current refresh token
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Refresh Rotate the refresh token and issue a new access token
	// (POST /auth/refresh)
	Refresh(ctx context.Context, request RefreshRequestObject) (RefreshResponseObject, error)
	// ListBrands Brands, sorted by name
	// (GET /brands)
	ListBrands(ctx context.Context, request ListBrandsRequestObject) (ListBrandsResponseObject, error)
	// CreateBrand Create a brand
	// (POST /brands)
	CreateBrand(ctx context.Context, request CreateBrandRequestObject) (CreateBrandResponseObject, error)
	// ArchiveBrand Archive a brand
	// (DELETE /brands/{id})
	ArchiveBrand(ctx context.Context, request ArchiveBrandRequestObject) (ArchiveBrandResponseObject, error)
	// GetBrand One brand
	// (GET /brands/{id})
	GetBrand(ctx context.Context, request GetBrandRequestObject) (GetBrandResponseObject, error)
	// UpdateBrand Rename a brand
	// (PATCH /brands/{id})
	UpdateBrand(ctx context.Context, request UpdateBrandRequestObject) (UpdateBrandResponseObject, error)
	// ListCategories Categories, flat, sorted by kind then path
	// (GET /categories)
	ListCategories(ctx context.Context, request ListCategoriesRequestObject) (ListCategoriesResponseObject, error)
	// CreateCategory Create a category
	// (POST /categories)
	CreateCategory(ctx context.Context, request CreateCategoryRequestObject) (CreateCategoryResponseObject, error)
	// ArchiveCategory Archive a category
	// (DELETE /categories/{id})
	ArchiveCategory(ctx context.Context, request ArchiveCategoryRequestObject) (ArchiveCategoryResponseObject, error)
	// GetCategory One category, with the counts the move dialog needs
	// (GET /categories/{id})
	GetCategory(ctx context.Context, request GetCategoryRequestObject) (GetCategoryResponseObject, error)
	// UpdateCategory Rename or move a category
	// (PATCH /categories/{id})
	UpdateCategory(ctx context.Context, request UpdateCategoryRequestObject) (UpdateCategoryResponseObject, error)
	// ListRoles The four seeded roles and the permissions each grants
	// (GET /roles)
	ListRoles(ctx context.Context, request ListRolesRequestObject) (ListRolesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Refresh operation middleware
func (sh *strictHandler) Refresh(w http.ResponseWriter, r *http.Request) {
	var request RefreshRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Refresh(ctx, request.(RefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Refresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshResponseObject); ok {
		if err := validResponse.VisitRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListBrands operation middleware
func (sh *strictHandler) ListBrands(w http.ResponseWriter, r *http.Request, params ListBrandsParams) {
	var request ListBrandsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBrands(ctx, request.(ListBrandsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBrands")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBrandsResponseObject); ok {
		if err := validResponse.VisitListBrandsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateBrand operation middleware
func (sh *strictHandler) CreateBrand(w http.ResponseWriter, r *http.Request) {
	var request CreateBrandRequestObject

	var body CreateBrandJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateBrand(ctx, request.(CreateBrandRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateBrand")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateBrandResponseObject); ok {
		if err := validResponse.VisitCreateBrandResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ArchiveBrand operation middleware
func (sh *strictHandler) ArchiveBrand(w http.ResponseWriter, r *http.Request, id Id) {
	var request ArchiveBrandRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ArchiveBrand(ctx, request.(ArchiveBrandRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ArchiveBrand")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ArchiveBrandResponseObject); ok {
		if err := validResponse.VisitArchiveBrandResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBrand operation middleware
func (sh *strictHandler) GetBrand(w http.ResponseWriter, r *http.Request, id Id) {
	var request GetBrandRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBrand(ctx, request.(GetBrandRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBrand")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBrandResponseObject); ok {
		if err := validResponse.VisitGetBrandResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateBrand operation middleware
func (sh *strictHandler) UpdateBrand(w http.ResponseWriter, r *http.Request, id Id) {
	var request UpdateBrandRequestObject

	request.Id = id

	var body UpdateBrandJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateBrand(ctx, request.(UpdateBrandRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateBrand")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateBrandResponseObject); ok {
		if err := validResponse.VisitUpdateBrandResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCategories operation middleware
func (sh *strictHandler) ListCategories(w http.ResponseWriter, r *http.Request, params ListCategoriesParams) {
	var request ListCategoriesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCategories(ctx, request.(ListCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCategories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCategoriesResponseObject); ok {
		if err := validResponse.VisitListCategoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCategory operation middleware
func (sh *strictHandler) CreateCategory(w http.ResponseWriter, r *http.Request) {
	var request CreateCategoryRequestObject

	var body CreateCategoryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCategory(ctx, request.(CreateCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCategory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCategoryResponseObject); ok {
		if err := validResponse.VisitCreateCategoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ArchiveCategory operation middleware
func (sh *strictHandler) ArchiveCategory(w http.ResponseWriter, r *http.Request, id Id) {
	var request ArchiveCategoryRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ArchiveCategory(ctx, request.(ArchiveCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ArchiveCategory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ArchiveCategoryResponseObject); ok {
		if err := validResponse.VisitArchiveCategoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCategory operation middleware
func (sh *strictHandler) GetCategory(w http.ResponseWriter, r *http.Request, id Id) {
	var request GetCategoryRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCategory(ctx, request.(GetCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCategory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCategoryResponseObject); ok {
		if err := validResponse.VisitGetCategoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCategory operation middleware
func (sh *strictHandler) UpdateCategory(w http.ResponseWriter, r *http.Request, id Id) {
	var request UpdateCategoryRequestObject

	request.Id = id

	var body UpdateCategoryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCategory(ctx, request.(UpdateCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCategory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateCategoryResponseObject); ok {
		if err := validResponse.VisitUpdateCategoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRoles operation middleware
func (sh *strictHandler) ListRoles(w http.ResponseWriter, r *http.Request) {
	var request ListRolesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRoles(ctx, request.(ListRolesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRoles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRolesResponseObject); ok {
		if err := validResponse.VisitListRolesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
