// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (tenant_id, actor_id, action, subject_type, subject_id, before, after, ip)
VALUES (current_setting('app.tenant_id')::uuid,
        $1, $2, $3, $4,
        $5, $6, $7)
`

type InsertAuditLogParams struct {
	ActorID     *uuid.UUID
	Action      string
	SubjectType string
	SubjectID   string
	Before      []byte
	After       []byte
	Ip          *netip.Addr
}

// tenant_id comes from the transaction's own tenant setting rather than a
// parameter, so an audit row cannot name a tenant other than the one whose
// write it records. RLS's WITH CHECK would refuse a mismatch anyway.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Before,
		arg.After,
		arg.Ip,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT a.id, a.action, a.actor_id, u.name AS actor_name, a.subject_type, a.subject_id,
       a.before, a.after, coalesce(host(a.ip), '')::text AS ip, a.created_at
FROM audit_log a
LEFT JOIN users u ON u.id = a.actor_id
WHERE ($1::text IS NULL OR a.subject_type = $1::text)
  AND ($2::text IS NULL OR a.subject_id = $2::text)
  AND ($3::uuid IS NULL OR a.actor_id = $3::uuid)
  AND ($4::timestamptz IS NULL OR a.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR a.created_at < $5::timestamptz)
  AND ($6::timestamptz IS NULL
       OR (a.created_at, a.id) < ($6::timestamptz, $7::bigint))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $8
`

type ListAuditParams struct {
	SubjectType *string
	SubjectID   *string
	ActorID     *uuid.UUID
	FromAt      *time.Time
	ToAt        *time.Time
	BeforeAt    *time.Time
	BeforeID    *int64
	Lim         int32
}

type ListAuditRow struct {
	ID          int64
	Action      string
	ActorID     *uuid.UUID
	ActorName   *string
	SubjectType string
	SubjectID   string
	Before      []byte
	After       []byte
	Ip          string
	CreatedAt   time.Time
}

// Newest first over (created_at, id); the id stays internal (BR-005) and is
// only the cursor's tie-break.
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]ListAuditRow, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.SubjectType,
		arg.SubjectID,
		arg.ActorID,
		arg.FromAt,
		arg.ToAt,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditRow
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.ActorID,
			&i.ActorName,
			&i.SubjectType,
			&i.SubjectID,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderAuditTrail = `-- name: OrderAuditTrail :many
SELECT a.action, a.actor_id, u.name AS actor_name, a.before, a.after, a.created_at
FROM audit_log a
LEFT JOIN users u ON u.id = a.actor_id
WHERE a.subject_type = 'order' AND a.subject_id = $1
ORDER BY a.created_at DESC, a.id DESC
`

type OrderAuditTrailRow struct {
	Action    string
	ActorID   *uuid.UUID
	ActorName *string
	Before    []byte
	After     []byte
	CreatedAt time.Time
}

// The order detail embeds its own trail (04-api-spec.md §5.2): readable with
// orders:read alone, so ops see it without audit_log:read.
func (q *Queries) OrderAuditTrail(ctx context.Context, subjectID string) ([]OrderAuditTrailRow, error) {
	rows, err := q.db.Query(ctx, orderAuditTrail, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderAuditTrailRow
	for rows.Next() {
		var i OrderAuditTrailRow
		if err := rows.Scan(
			&i.Action,
			&i.ActorID,
			&i.ActorName,
			&i.Before,
			&i.After,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
