// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (tenant_id, actor_id, action, subject_type, subject_id, before, after, ip)
VALUES (current_setting('app.tenant_id')::uuid,
        $1, $2, $3, $4,
        $5, $6, $7)
`

type InsertAuditLogParams struct {
	ActorID     *uuid.UUID
	Action      string
	SubjectType string
	SubjectID   string
	Before      []byte
	After       []byte
	Ip          *netip.Addr
}

// tenant_id comes from the transaction's own tenant setting rather than a
// parameter, so an audit row cannot name a tenant other than the one whose
// write it records. RLS's WITH CHECK would refuse a mismatch anyway.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Before,
		arg.After,
		arg.Ip,
	)
	return err
}
