// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, tenant_id, user_id, token_hash, rotated_from, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateRefreshTokenParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	UserID      uuid.UUID
	TokenHash   string
	RotatedFrom *uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.RotatedFrom,
		arg.ExpiresAt,
	)
	return err
}

const getSession = `-- name: GetSession :one

SELECT u.id AS user_id, u.name AS user_name, u.role,
       t.id AS tenant_id, t.name AS tenant_name, t.timezone, t.currency
  FROM users u
  JOIN tenants t ON t.id = u.tenant_id
 WHERE u.id = $1
`

type GetSessionRow struct {
	UserID     uuid.UUID
	UserName   string
	Role       string
	TenantID   uuid.UUID
	TenantName string
	Timezone   string
	Currency   string
}

// Queries over the auth tables.
//
// The two cross-tenant lookups are NOT here. They are hand-written in
// internal/db/auth_lookup.go so that the only two reads in the system that
// cross a tenant boundary are visible as such, rather than sitting among
// generated code that all looks alike.
// Everything the Session response needs, in one round trip. Runs inside
// InTenantTx, so RLS has already scoped users; tenants has no RLS by design.
func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Role,
		&i.TenantID,
		&i.TenantName,
		&i.Timezone,
		&i.Currency,
	)
	return i, err
}

const hasSuccessor = `-- name: HasSuccessor :one
SELECT EXISTS (SELECT 1 FROM refresh_tokens WHERE rotated_from = $1)
`

// Whether some other token was created by rotating this one.
//
// This is what separates theft from an ordinary sign-out. Both leave a token
// with revoked_at set, so revoked_at alone cannot tell them apart -- and
// treating a sign-out as theft means a stale browser tab replaying its old
// cookie signs the user out of every other device.
func (q *Queries) HasSuccessor(ctx context.Context, rotatedFrom *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasSuccessor, rotatedFrom)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :execrows
UPDATE refresh_tokens SET revoked_at = now()
 WHERE user_id = $1 AND revoked_at IS NULL
`

// Used when a already-rotated token is presented again, which means it was
// stolen. API spec.md 2: "the whole rotation chain is revoked and the user is
// signed out everywhere".
//
// This revokes every active token for the user, not only the chain the reused
// token belongs to. A chain starts at each login, so a user signed in on a
// phone and a laptop has two -- and revoking one of them would leave the
// thief's other session alive while claiming the user was signed out
// everywhere. The chain is a subset of this.
func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens SET revoked_at = now()
 WHERE id = $1 AND revoked_at IS NULL
`

// One token, by id. Used by logout, which has no reason to touch any other.
func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchLastLogin = `-- name: TouchLastLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchLastLogin, id)
	return err
}
