// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brands.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const archiveBrand = `-- name: ArchiveBrand :one
UPDATE brands SET archived_at = coalesce(archived_at, now()), updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, slug, archived_at, created_at, updated_at
`

// Archiving twice keeps the first timestamp.
func (q *Queries) ArchiveBrand(ctx context.Context, id uuid.UUID) (Brand, error) {
	row := q.db.QueryRow(ctx, archiveBrand, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearProductBrand = `-- name: ClearProductBrand :execrows
UPDATE products SET brand_id = NULL, version = version + 1, updated_at = now()
WHERE brand_id = $1
`

// Deleting a brand takes it off every product (BR-012). The version bump makes
// a product form still holding the brand get 409 instead of re-setting it.
func (q *Queries) ClearProductBrand(ctx context.Context, brandID *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearProductBrand, brandID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createBrand = `-- name: CreateBrand :one
INSERT INTO brands (id, tenant_id, name, slug)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2,
        coalesce($3::text, slugify($2)))
RETURNING id, tenant_id, name, slug, archived_at, created_at, updated_at
`

type CreateBrandParams struct {
	ID   uuid.UUID
	Name string
	Slug *string
}

// A NULL slug means slugify(name) (BR-030).
func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, createBrand, arg.ID, arg.Name, arg.Slug)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrand = `-- name: GetBrand :one
SELECT id, tenant_id, name, slug, archived_at, created_at, updated_at FROM brands WHERE id = $1
`

func (q *Queries) GetBrand(ctx context.Context, id uuid.UUID) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrand, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT id, tenant_id, name, slug, archived_at, created_at, updated_at FROM brands
WHERE (archived_at IS NOT NULL) = $1::bool
  AND ($2::text IS NULL OR name ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL
       OR (name, id) > ($3::text, $4::uuid))
ORDER BY name, id
LIMIT $5
`

type ListBrandsParams struct {
	Archived  bool
	Q         *string
	AfterName *string
	AfterID   *uuid.UUID
	Lim       int32
}

// Keyset over (name, id). q is a substring match on the name; the caller
// escapes LIKE metacharacters.
func (q *Queries) ListBrands(ctx context.Context, arg ListBrandsParams) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands,
		arg.Archived,
		arg.Q,
		arg.AfterName,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Slug,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugify = `-- name: Slugify :one

SELECT slugify($1::text)::text
`

// Brands (P1-021, 04-api-spec.md §6.1). Every query runs inside InTenantTx,
// so RLS has already narrowed it to one tenant.
func (q *Queries) Slugify(ctx context.Context, txt string) (string, error) {
	row := q.db.QueryRow(ctx, slugify, txt)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE brands SET name = $1,
                  slug = coalesce($2::text, slugify($1)), updated_at = now()
WHERE id = $3
RETURNING id, tenant_id, name, slug, archived_at, created_at, updated_at
`

type UpdateBrandParams struct {
	Name string
	Slug *string
	ID   uuid.UUID
}

// A NULL slug re-derives it from the name (BR-030).
func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, updateBrand, arg.Name, arg.Slug, arg.ID)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
