// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const archiveCategory = `-- name: ArchiveCategory :exec
UPDATE categories SET archived_at = coalesce(archived_at, now()), updated_at = now() WHERE id = $1
`

func (q *Queries) ArchiveCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveCategory, id)
	return err
}

const categoryCounts = `-- name: CategoryCounts :one
SELECT
  (SELECT count(*) FROM categories d
    WHERE d.kind = c.kind AND d.path <@ c.path AND d.id <> c.id AND d.archived_at IS NULL)::int AS descendant_count,
  (SELECT count(DISTINCT pc.product_id) FROM product_categories pc
     JOIN categories d ON d.id = pc.category_id
     JOIN products p ON p.id = pc.product_id
    WHERE d.kind = c.kind AND d.path <@ c.path AND p.archived_at IS NULL)::int AS product_count
FROM categories c WHERE c.id = $1
`

type CategoryCountsRow struct {
	DescendantCount int32
	ProductCount    int32
}

// Live categories below this one, and live products linked anywhere in its
// subtree -- what the move and delete dialogs state. Live children block a
// delete (BR-036).
func (q *Queries) CategoryCounts(ctx context.Context, id uuid.UUID) (CategoryCountsRow, error) {
	row := q.db.QueryRow(ctx, categoryCounts, id)
	var i CategoryCountsRow
	err := row.Scan(&i.DescendantCount, &i.ProductCount)
	return i, err
}

const clearCategoryProducts = `-- name: ClearCategoryProducts :execrows
WITH unlinked AS (
  DELETE FROM product_categories WHERE category_id = $1 RETURNING product_id
)
UPDATE products SET version = version + 1, updated_at = now()
 WHERE id IN (SELECT product_id FROM unlinked)
`

// Deleting a category takes it off its products, bumping their version so a
// stale product form gets 409 instead of putting it back (BR-012).
func (q *Queries) ClearCategoryProducts(ctx context.Context, categoryID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearCategoryProducts, categoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, tenant_id, parent_id, kind, name, label)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3, $4, $5)
RETURNING id, tenant_id, parent_id, kind, name, path, archived_at, created_at, updated_at, label
`

type CreateCategoryParams struct {
	ID       uuid.UUID
	ParentID *uuid.UUID
	Kind     string
	Name     string
	Label    *string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.ParentID,
		arg.Kind,
		arg.Name,
		arg.Label,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.Path,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, tenant_id, parent_id, kind, name, path, archived_at, created_at, updated_at, label FROM categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.Path,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT c.id, c.tenant_id, c.parent_id, c.kind, c.name, c.path, c.archived_at, c.created_at, c.updated_at, c.label FROM categories c
LEFT JOIN categories base ON base.id = $1::uuid
WHERE c.archived_at IS NULL
  AND ($2::text IS NULL OR c.kind = $2::text)
  AND ($1::uuid IS NULL
       OR (c.kind = base.kind AND c.path <@ base.path AND c.id <> base.id))
  AND ($3::int IS NULL
       OR nlevel(c.path) <= coalesce(nlevel(base.path), 0) + $3::int)
ORDER BY c.kind, c.path
`

type ListCategoriesParams struct {
	ParentID *uuid.UUID
	Kind     *string
	Depth    *int32
}

// Flat, by kind then path. Below parent_id when given; depth counts levels
// below the parent, or below the roots without one.
func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.ParentID, arg.Kind, arg.Depth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.Path,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCategories = `-- name: LockCategories :exec

SELECT pg_advisory_xact_lock(hashtextextended('categories:' || current_setting('app.tenant_id'), 0))
`

// Categories (P1-024, 04-api-spec.md §6.2). path is maintained by the
// triggers of migrations 000009/000010; nothing here writes it.
// Serialises category writes per tenant, so two crossing moves cannot both
// pass the cycle check against the other's old tree (BR-034).
func (q *Queries) LockCategories(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockCategories)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
   SET name      = CASE WHEN $1::bool THEN $2::text ELSE name END,
       parent_id = CASE WHEN $3::bool THEN $4::uuid ELSE parent_id END,
       label     = CASE WHEN $5::bool THEN $6::text ELSE label END,
       updated_at = now()
 WHERE id = $7
RETURNING id, tenant_id, parent_id, kind, name, path, archived_at, created_at, updated_at, label
`

type UpdateCategoryParams struct {
	SetName   bool
	Name      string
	SetParent bool
	ParentID  *uuid.UUID
	SetLabel  bool
	Label     *string
	ID        uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.SetName,
		arg.Name,
		arg.SetParent,
		arg.ParentID,
		arg.SetLabel,
		arg.Label,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.Path,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
	)
	return i, err
}
