// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getCustomer = `-- name: GetCustomer :one

SELECT c.id, c.name, c.email, c.phone, c.created_at,
       (SELECT count(*)::int FROM orders o WHERE o.customer_id = c.id) AS order_count
FROM customers c WHERE c.id = $1
`

type GetCustomerRow struct {
	ID         uuid.UUID
	Name       string
	Email      string
	Phone      *string
	CreatedAt  time.Time
	OrderCount int32
}

// Customers (P1-106, 04-api-spec.md §5.5). Read-only: staff never create
// accounts, set passwords or see hashes (BR-092) -- the SELECTs name their
// columns so password_hash cannot ride along.
func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (GetCustomerRow, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i GetCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.OrderCount,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT c.id, c.name, c.email, c.phone, c.created_at,
       (SELECT count(*)::int FROM orders o WHERE o.customer_id = c.id) AS order_count
FROM customers c
WHERE ($1::text IS NULL
       OR c.name ILIKE '%' || $1 || '%'
       OR c.email ILIKE '%' || $1 || '%'
       OR c.phone ILIKE '%' || $1 || '%')
  AND ($2::uuid IS NULL OR c.id < $2::uuid)
ORDER BY c.id DESC
LIMIT $3
`

type ListCustomersParams struct {
	Q        *string
	BeforeID *uuid.UUID
	Lim      int32
}

type ListCustomersRow struct {
	ID         uuid.UUID
	Name       string
	Email      string
	Phone      *string
	CreatedAt  time.Time
	OrderCount int32
}

// Keyset on id DESC: v7 ids are time-ordered, so newest first.
func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Q, arg.BeforeID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersRow
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
			&i.OrderCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
