// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createJob = `-- name: CreateJob :one

INSERT INTO jobs (id, tenant_id, kind, params, created_by)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3, $4)
RETURNING id, tenant_id, kind, state, processed, total, failed, params, result, error, created_by, created_at, finished_at
`

type CreateJobParams struct {
	ID        uuid.UUID
	Kind      string
	Params    []byte
	CreatedBy *uuid.UUID
}

// Jobs (P1-060, BR-060). Every query runs in the job's tenant.
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.Kind,
		arg.Params,
		arg.CreatedBy,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.State,
		&i.Processed,
		&i.Total,
		&i.Failed,
		&i.Params,
		&i.Result,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs SET state = 'failed', error = $1, finished_at = now()
WHERE id = $2 AND state IN ('queued', 'running')
`

type FailJobParams struct {
	Error []byte
	ID    uuid.UUID
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.Error, arg.ID)
	return err
}

const finishJob = `-- name: FinishJob :exec
UPDATE jobs SET state = 'done', result = $1, finished_at = now()
WHERE id = $2 AND state = 'running'
`

type FinishJobParams struct {
	Result []byte
	ID     uuid.UUID
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.Exec(ctx, finishJob, arg.Result, arg.ID)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, tenant_id, kind, state, processed, total, failed, params, result, error, created_by, created_at, finished_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.State,
		&i.Processed,
		&i.Total,
		&i.Failed,
		&i.Params,
		&i.Result,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const jobProgress = `-- name: JobProgress :exec
UPDATE jobs SET processed = $1, total = $2, failed = $3
WHERE id = $4 AND state = 'running'
`

type JobProgressParams struct {
	Processed int32
	Total     *int32
	Failed    int32
	ID        uuid.UUID
}

func (q *Queries) JobProgress(ctx context.Context, arg JobProgressParams) error {
	_, err := q.db.Exec(ctx, jobProgress,
		arg.Processed,
		arg.Total,
		arg.Failed,
		arg.ID,
	)
	return err
}

const startJob = `-- name: StartJob :one
UPDATE jobs SET state = 'running' WHERE id = $1 AND state IN ('queued', 'running') RETURNING id, tenant_id, kind, state, processed, total, failed, params, result, error, created_by, created_at, finished_at
`

// The guard that makes a redelivered job finish once: a job already done or
// failed is not started again.
func (q *Queries) StartJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, startJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.State,
		&i.Processed,
		&i.Total,
		&i.Failed,
		&i.Params,
		&i.Result,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
