// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createMedia = `-- name: CreateMedia :one

INSERT INTO product_media (id, tenant_id, product_id, variant_id, r2_key, mime_type, bytes, position)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3,
        $4, $5, $6,
        (SELECT coalesce(max(position) + 1, 0) FROM product_media WHERE product_id = $2))
ON CONFLICT (product_id, r2_key) DO NOTHING
RETURNING id, tenant_id, product_id, variant_id, r2_key, mime_type, bytes, width, height, position, derivatives, source_url, created_at
`

type CreateMediaParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	VariantID *uuid.UUID
	R2Key     string
	MimeType  string
	Bytes     int64
}

// Product media (P1-043, 04-api-spec.md §8). Rows hold object keys, never
// URLs (BR-050).
// Appended after the product's other images. Confirming the same key twice is
// the same image: the conflict returns nothing and the caller reads the row.
func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (ProductMedium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.ID,
		arg.ProductID,
		arg.VariantID,
		arg.R2Key,
		arg.MimeType,
		arg.Bytes,
	)
	var i ProductMedium
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.VariantID,
		&i.R2Key,
		&i.MimeType,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.Position,
		&i.Derivatives,
		&i.SourceUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :one
DELETE FROM product_media WHERE id = $1 RETURNING id, tenant_id, product_id, variant_id, r2_key, mime_type, bytes, width, height, position, derivatives, source_url, created_at
`

func (q *Queries) DeleteMedia(ctx context.Context, id uuid.UUID) (ProductMedium, error) {
	row := q.db.QueryRow(ctx, deleteMedia, id)
	var i ProductMedium
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.VariantID,
		&i.R2Key,
		&i.MimeType,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.Position,
		&i.Derivatives,
		&i.SourceUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one
SELECT id, tenant_id, product_id, variant_id, r2_key, mime_type, bytes, width, height, position, derivatives, source_url, created_at FROM product_media WHERE id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id uuid.UUID) (ProductMedium, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i ProductMedium
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.VariantID,
		&i.R2Key,
		&i.MimeType,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.Position,
		&i.Derivatives,
		&i.SourceUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaByKey = `-- name: GetMediaByKey :one
SELECT id, tenant_id, product_id, variant_id, r2_key, mime_type, bytes, width, height, position, derivatives, source_url, created_at FROM product_media WHERE product_id = $1 AND r2_key = $2
`

type GetMediaByKeyParams struct {
	ProductID uuid.UUID
	R2Key     string
}

func (q *Queries) GetMediaByKey(ctx context.Context, arg GetMediaByKeyParams) (ProductMedium, error) {
	row := q.db.QueryRow(ctx, getMediaByKey, arg.ProductID, arg.R2Key)
	var i ProductMedium
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.VariantID,
		&i.R2Key,
		&i.MimeType,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.Position,
		&i.Derivatives,
		&i.SourceUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listProductMedia = `-- name: ListProductMedia :many
SELECT id, tenant_id, product_id, variant_id, r2_key, mime_type, bytes, width, height, position, derivatives, source_url, created_at FROM product_media WHERE product_id = $1 ORDER BY position, id
`

func (q *Queries) ListProductMedia(ctx context.Context, productID uuid.UUID) ([]ProductMedium, error) {
	rows, err := q.db.Query(ctx, listProductMedia, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductMedium
	for rows.Next() {
		var i ProductMedium
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.VariantID,
			&i.R2Key,
			&i.MimeType,
			&i.Bytes,
			&i.Width,
			&i.Height,
			&i.Position,
			&i.Derivatives,
			&i.SourceUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveVariantOfProduct = `-- name: LiveVariantOfProduct :one
SELECT EXISTS (SELECT 1 FROM variants WHERE id = $1 AND product_id = $2 AND archived_at IS NULL)
`

type LiveVariantOfProductParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) LiveVariantOfProduct(ctx context.Context, arg LiveVariantOfProductParams) (bool, error) {
	row := q.db.QueryRow(ctx, liveVariantOfProduct, arg.ID, arg.ProductID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const mediaKeyInUse = `-- name: MediaKeyInUse :one
SELECT EXISTS (SELECT 1 FROM product_media WHERE r2_key = $1)
`

func (q *Queries) MediaKeyInUse(ctx context.Context, r2Key string) (bool, error) {
	row := q.db.QueryRow(ctx, mediaKeyInUse, r2Key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setMediaDerivatives = `-- name: SetMediaDerivatives :execrows
UPDATE product_media SET derivatives = $1, width = $2, height = $3
WHERE id = $4
`

type SetMediaDerivativesParams struct {
	Derivatives []byte
	Width       *int32
	Height      *int32
	ID          uuid.UUID
}

// The worker's result for one image (P1-044).
func (q *Queries) SetMediaDerivatives(ctx context.Context, arg SetMediaDerivativesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMediaDerivatives,
		arg.Derivatives,
		arg.Width,
		arg.Height,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMediaPosition = `-- name: SetMediaPosition :exec
UPDATE product_media SET position = $1 WHERE id = $2
`

type SetMediaPositionParams struct {
	Position int32
	ID       uuid.UUID
}

func (q *Queries) SetMediaPosition(ctx context.Context, arg SetMediaPositionParams) error {
	_, err := q.db.Exec(ctx, setMediaPosition, arg.Position, arg.ID)
	return err
}

const setMediaVariant = `-- name: SetMediaVariant :one
UPDATE product_media SET variant_id = $1 WHERE id = $2 RETURNING id, tenant_id, product_id, variant_id, r2_key, mime_type, bytes, width, height, position, derivatives, source_url, created_at
`

type SetMediaVariantParams struct {
	VariantID *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SetMediaVariant(ctx context.Context, arg SetMediaVariantParams) (ProductMedium, error) {
	row := q.db.QueryRow(ctx, setMediaVariant, arg.VariantID, arg.ID)
	var i ProductMedium
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.VariantID,
		&i.R2Key,
		&i.MimeType,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.Position,
		&i.Derivatives,
		&i.SourceUrl,
		&i.CreatedAt,
	)
	return i, err
}
