// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Name          string
	KeyHash       string
	AllowedOrigin string
	LastUsedAt    *time.Time
	RevokedAt     *time.Time
	CreatedBy     *uuid.UUID
	CreatedAt     time.Time
}

type AuditLog struct {
	ID          int64
	TenantID    uuid.UUID
	ActorID     *uuid.UUID
	Action      string
	SubjectType string
	SubjectID   string
	Before      []byte
	After       []byte
	Ip          *netip.Addr
	CreatedAt   time.Time
}

type Brand struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	Slug       string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Category struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	ParentID   *uuid.UUID
	Kind       string
	Name       string
	Path       string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Label      *string
}

type Customer struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	Email           string
	PasswordHash    *string
	Name            string
	Phone           *string
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Job struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Kind       string
	State      string
	Processed  int32
	Total      *int32
	Failed     int32
	Params     []byte
	Result     []byte
	Error      []byte
	CreatedBy  *uuid.UUID
	CreatedAt  time.Time
	FinishedAt *time.Time
}

type Order struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	Source          string
	CustomerID      *uuid.UUID
	OrderNumber     string
	Status          string
	Customer        []byte
	ShippingAddress []byte
	Note            *string
	SubtotalAmount  int64
	ShippingAmount  int64
	DiscountAmount  int64
	TotalAmount     int64
	Currency        string
	PaymentMethod   string
	ShippingCourier *string
	ShippingService *string
	Courier         *string
	TrackingNumber  *string
	PlacedAt        time.Time
	PaidAt          *time.Time
	ShippedAt       *time.Time
	CompletedAt     *time.Time
	CancelledAt     *time.Time
	RefundedAt      *time.Time
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type OrderLine struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	OrderID        uuid.UUID
	VariantID      uuid.UUID
	SkuSnapshot    string
	TitleSnapshot  string
	Qty            int32
	UnitPrice      int64
	DiscountAmount int64
}

type OrderSequence struct {
	TenantID  uuid.UUID
	LastValue int64
}

type Product struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Title       string
	Slug        string
	Description *string
	BrandID     *uuid.UUID
	Status      string
	Attributes  []byte
	OptionNames []string
	Version     int32
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProductCategory struct {
	TenantID   uuid.UUID
	ProductID  uuid.UUID
	CategoryID uuid.UUID
}

type ProductMedium struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ProductID   uuid.UUID
	VariantID   *uuid.UUID
	R2Key       string
	MimeType    string
	Bytes       int64
	Width       *int32
	Height      *int32
	Position    int32
	Derivatives []byte
	SourceUrl   *string
	CreatedAt   time.Time
}

type RefreshToken struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	UserID      uuid.UUID
	TokenHash   string
	RotatedFrom *uuid.UUID
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type Tenant struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Timezone    string
	Status      string
	CreatedAt   time.Time
	OrderPrefix string
}

type User struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Email        string
	PasswordHash *string
	Name         string
	Role         string
	Status       string
	LastLoginAt  *time.Time
	CreatedAt    time.Time
}

type Variant struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	ProductID          uuid.UUID
	Sku                *string
	Barcode            *string
	OptionValues       []string
	RegularPriceAmount int64
	SalePriceAmount    *int64
	SaleStartsAt       *time.Time
	SaleEndsAt         *time.Time
	Currency           string
	WeightGrams        int32
	ArchivedAt         *time.Time
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
