// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Name          string
	KeyHash       string
	AllowedOrigin string
	LastUsedAt    *time.Time
	RevokedAt     *time.Time
	CreatedBy     *uuid.UUID
	CreatedAt     time.Time
}

type AuditLog struct {
	ID          int64
	TenantID    uuid.UUID
	ActorID     *uuid.UUID
	Action      string
	SubjectType string
	SubjectID   string
	Before      []byte
	After       []byte
	Ip          *netip.Addr
	CreatedAt   time.Time
}

type RefreshToken struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	UserID      uuid.UUID
	TokenHash   string
	RotatedFrom *uuid.UUID
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type Tenant struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Timezone    string
	Status      string
	CreatedAt   time.Time
	OrderPrefix string
}

type User struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Email        string
	PasswordHash *string
	Name         string
	Role         string
	Status       string
	LastLoginAt  *time.Time
	CreatedAt    time.Time
}
