// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	KeyHash     string
	KeyPrefix   string
	Permissions []string
	CreatedBy   *uuid.UUID
	LastUsedAt  *time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type RefreshToken struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	UserID      uuid.UUID
	TokenHash   string
	RotatedFrom *uuid.UUID
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Timezone  string
	Currency  string
	Status    string
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Email        string
	PasswordHash *string
	Name         string
	Role         string
	Status       string
	LastLoginAt  *time.Time
	CreatedAt    time.Time
}
