// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getOrder = `-- name: GetOrder :one
SELECT id, tenant_id, source, customer_id, order_number, status, customer, shipping_address, note, subtotal_amount, shipping_amount, discount_amount, total_amount, currency, payment_method, shipping_courier, shipping_service, courier, tracking_number, placed_at, paid_at, shipped_at, completed_at, cancelled_at, refunded_at, version, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.Customer,
		&i.ShippingAddress,
		&i.Note,
		&i.SubtotalAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.Currency,
		&i.PaymentMethod,
		&i.ShippingCourier,
		&i.ShippingService,
		&i.Courier,
		&i.TrackingNumber,
		&i.PlacedAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.RefundedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockOrder = `-- name: LockOrder :one

SELECT id, tenant_id, source, customer_id, order_number, status, customer, shipping_address, note, subtotal_amount, shipping_amount, discount_amount, total_amount, currency, payment_method, shipping_courier, shipping_service, courier, tracking_number, placed_at, paid_at, shipped_at, completed_at, cancelled_at, refunded_at, version, created_at, updated_at FROM orders WHERE id = $1 FOR UPDATE
`

// Orders (Phase 2, 04-api-spec.md §5). Status changes only through the one
// Transition in internal/orders (BR-071): it takes the row lock below, checks
// the allow-list and is the only caller of TransitionOrder. A bare
// "UPDATE orders SET status" anywhere else is a bug by definition.
func (q *Queries) LockOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, lockOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.Customer,
		&i.ShippingAddress,
		&i.Note,
		&i.SubtotalAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.Currency,
		&i.PaymentMethod,
		&i.ShippingCourier,
		&i.ShippingService,
		&i.Courier,
		&i.TrackingNumber,
		&i.PlacedAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.RefundedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordRefund = `-- name: RecordRefund :one
UPDATE orders SET refunded_at = now(), version = version + 1, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, source, customer_id, order_number, status, customer, shipping_address, note, subtotal_amount, shipping_amount, discount_amount, total_amount, currency, payment_method, shipping_courier, shipping_service, courier, tracking_number, placed_at, paid_at, shipped_at, completed_at, cancelled_at, refunded_at, version, created_at, updated_at
`

// BR-075. Not a transition: the status stays cancelled. The caller holds the
// row lock and has checked cancelled + paid + not yet refunded; the table
// CHECK refuses anything else regardless.
func (q *Queries) RecordRefund(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, recordRefund, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.Customer,
		&i.ShippingAddress,
		&i.Note,
		&i.SubtotalAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.Currency,
		&i.PaymentMethod,
		&i.ShippingCourier,
		&i.ShippingService,
		&i.Courier,
		&i.TrackingNumber,
		&i.PlacedAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.RefundedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionOrder = `-- name: TransitionOrder :one
UPDATE orders SET
    status          = $1,
    paid_at         = CASE WHEN $1::text = 'paid'      THEN now() ELSE paid_at END,
    shipped_at      = CASE WHEN $1::text = 'shipped'   THEN now() ELSE shipped_at END,
    completed_at    = CASE WHEN $1::text = 'completed' THEN now() ELSE completed_at END,
    cancelled_at    = CASE WHEN $1::text = 'cancelled' THEN now() ELSE cancelled_at END,
    courier         = coalesce($2, courier),
    tracking_number = coalesce($3, tracking_number),
    version         = version + 1,
    updated_at      = now()
WHERE id = $4
RETURNING id, tenant_id, source, customer_id, order_number, status, customer, shipping_address, note, subtotal_amount, shipping_amount, discount_amount, total_amount, currency, payment_method, shipping_courier, shipping_service, courier, tracking_number, placed_at, paid_at, shipped_at, completed_at, cancelled_at, refunded_at, version, created_at, updated_at
`

type TransitionOrderParams struct {
	ToStatus       string
	Courier        *string
	TrackingNumber *string
	ID             uuid.UUID
}

// BR-071. Stamps the timestamp matching the target status (processing has
// none) and bumps version. courier and tracking_number arrive only on a ship
// (BR-072); coalesce keeps them on every other move.
func (q *Queries) TransitionOrder(ctx context.Context, arg TransitionOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, transitionOrder,
		arg.ToStatus,
		arg.Courier,
		arg.TrackingNumber,
		arg.ID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.CustomerID,
		&i.OrderNumber,
		&i.Status,
		&i.Customer,
		&i.ShippingAddress,
		&i.Note,
		&i.SubtotalAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.Currency,
		&i.PaymentMethod,
		&i.ShippingCourier,
		&i.ShippingService,
		&i.Courier,
		&i.TrackingNumber,
		&i.PlacedAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.RefundedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
