// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package sqlcgen

import (
	"context"
)

const getTenantBySlug = `-- name: GetTenantBySlug :one

SELECT id, name, slug, timezone, currency, status, created_at FROM tenants
WHERE slug = $1
`

// Queries over the platform tables.
//
// Reads only. The writes belong to the items that need them -- P1-011 for the
// auth path, P1-064 and P1-065 for user and API-key management -- and adding
// them here would be guessing at their shape.
// Reached from the auth path, before any tenant context exists. tenants has no
// RLS, deliberately: there would be nothing to scope it by.
func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, name, role, status, last_login_at, created_at FROM users
WHERE email = $1
`

// Runs inside InTenantTx, so RLS has already narrowed this to one tenant. The
// UNIQUE (tenant_id, email) constraint is what makes :one correct -- email
// alone is not unique across tenants.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}
