// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const addProductCategories = `-- name: AddProductCategories :exec
INSERT INTO product_categories (tenant_id, product_id, category_id)
SELECT current_setting('app.tenant_id')::uuid, $1, unnest($2::uuid[])
`

type AddProductCategoriesParams struct {
	ProductID   uuid.UUID
	CategoryIds []uuid.UUID
}

func (q *Queries) AddProductCategories(ctx context.Context, arg AddProductCategoriesParams) error {
	_, err := q.db.Exec(ctx, addProductCategories, arg.ProductID, arg.CategoryIds)
	return err
}

const archiveProduct = `-- name: ArchiveProduct :one
UPDATE products SET status = 'archived', archived_at = coalesce(archived_at, now()),
       version = version + 1, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, title, slug, description, brand_id, status, attributes, option_names, version, archived_at, created_at, updated_at
`

func (q *Queries) ArchiveProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, archiveProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BrandID,
		&i.Status,
		&i.Attributes,
		&i.OptionNames,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const bumpProduct = `-- name: BumpProduct :one
UPDATE products SET option_names = $1, version = version + 1, updated_at = now()
WHERE id = $2
RETURNING version
`

type BumpProductParams struct {
	OptionNames []string
	ID          uuid.UUID
}

// One version step per matrix save, with the option axes it settled on.
func (q *Queries) BumpProduct(ctx context.Context, arg BumpProductParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpProduct, arg.OptionNames, arg.ID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const clearProductCategories = `-- name: ClearProductCategories :exec
DELETE FROM product_categories WHERE product_id = $1
`

func (q *Queries) ClearProductCategories(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearProductCategories, productID)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, tenant_id, title, slug, description, brand_id, attributes)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3,
        $4, $5, $6)
RETURNING id, tenant_id, title, slug, description, brand_id, status, attributes, option_names, version, archived_at, created_at, updated_at
`

type CreateProductParams struct {
	ID          uuid.UUID
	Title       string
	Slug        string
	Description *string
	BrandID     *uuid.UUID
	Attributes  []byte
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.BrandID,
		arg.Attributes,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BrandID,
		&i.Status,
		&i.Attributes,
		&i.OptionNames,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, tenant_id, title, slug, description, brand_id, status, attributes, option_names, version, archived_at, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BrandID,
		&i.Status,
		&i.Attributes,
		&i.OptionNames,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const liveCategoryCount = `-- name: LiveCategoryCount :one
SELECT count(*)::int FROM categories WHERE id = ANY($1::uuid[]) AND archived_at IS NULL
`

func (q *Queries) LiveCategoryCount(ctx context.Context, ids []uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, liveCategoryCount, ids)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const liveVariantCount = `-- name: LiveVariantCount :one
SELECT count(*)::int FROM variants WHERE product_id = $1 AND archived_at IS NULL
`

func (q *Queries) LiveVariantCount(ctx context.Context, productID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, liveVariantCount, productID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const lockProduct = `-- name: LockProduct :one
SELECT id, tenant_id, title, slug, description, brand_id, status, attributes, option_names, version, archived_at, created_at, updated_at FROM products WHERE id = $1 FOR UPDATE
`

// The matrix holds the product row for its whole transaction, so two grid
// saves cannot interleave.
func (q *Queries) LockProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, lockProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BrandID,
		&i.Status,
		&i.Attributes,
		&i.OptionNames,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const productCategories = `-- name: ProductCategories :many
SELECT c.id, c.kind, c.name, c.path FROM product_categories pc
JOIN categories c ON c.id = pc.category_id
WHERE pc.product_id = $1
ORDER BY c.kind, c.path
`

type ProductCategoriesRow struct {
	ID   uuid.UUID
	Kind string
	Name string
	Path string
}

func (q *Queries) ProductCategories(ctx context.Context, productID uuid.UUID) ([]ProductCategoriesRow, error) {
	rows, err := q.db.Query(ctx, productCategories, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategoriesRow
	for rows.Next() {
		var i ProductCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productSlugTaken = `-- name: ProductSlugTaken :one

SELECT EXISTS (SELECT 1 FROM products WHERE slug = $1 AND id IS DISTINCT FROM $2::uuid)
`

type ProductSlugTakenParams struct {
	Slug     string
	ExceptID *uuid.UUID
}

// Products (P1-028, 04-api-spec.md §7.1).
// Archived products keep their slug (BR-042), so they count.
func (q *Queries) ProductSlugTaken(ctx context.Context, arg ProductSlugTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, productSlugTaken, arg.Slug, arg.ExceptID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const publishFacts = `-- name: PublishFacts :one
SELECT
  (SELECT count(*) FROM product_media m WHERE m.product_id = $1)::int AS media,
  (SELECT count(*) FROM product_categories pc JOIN categories c ON c.id = pc.category_id
    WHERE pc.product_id = $1 AND c.kind = 'category')::int AS main_categories
`

type PublishFactsRow struct {
	Media          int32
	MainCategories int32
}

// What the publish check reads about a product (BR-038).
func (q *Queries) PublishFacts(ctx context.Context, id uuid.UUID) (PublishFactsRow, error) {
	row := q.db.QueryRow(ctx, publishFacts, id)
	var i PublishFactsRow
	err := row.Scan(&i.Media, &i.MainCategories)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
  title       = coalesce($1, title),
  slug        = coalesce($2, slug),
  description = CASE WHEN $3::bool THEN $4 ELSE description END,
  brand_id    = CASE WHEN $5::bool THEN $6::uuid ELSE brand_id END,
  attributes  = coalesce($7, attributes),
  status      = coalesce($8, status),
  version     = version + 1,
  updated_at  = now()
WHERE id = $9 AND version = $10
RETURNING id, tenant_id, title, slug, description, brand_id, status, attributes, option_names, version, archived_at, created_at, updated_at
`

type UpdateProductParams struct {
	Title          *string
	Slug           *string
	SetDescription bool
	Description    *string
	SetBrand       bool
	BrandID        *uuid.UUID
	Attributes     []byte
	Status         *string
	ID             uuid.UUID
	Version        int32
}

// Optimistic concurrency (BR-010): zero rows means a stale version or no row.
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Title,
		arg.Slug,
		arg.SetDescription,
		arg.Description,
		arg.SetBrand,
		arg.BrandID,
		arg.Attributes,
		arg.Status,
		arg.ID,
		arg.Version,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BrandID,
		&i.Status,
		&i.Attributes,
		&i.OptionNames,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
