// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getTenant = `-- name: GetTenant :one
SELECT id, name, slug, timezone, status, created_at, order_prefix FROM tenants WHERE id = $1
`

// tenants has no RLS; the id comes from the caller's own tenant context.
func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.OrderPrefix,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, tenant_id, email, password_hash, name, role, status, last_login_at, created_at FROM users WHERE id = $1
`

// Team: users and the tenant's own settings (P1-064, P1-071, P1-226).
func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}
