// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE users SET password_hash = $1, status = 'active'
WHERE id = $2 AND status = 'invited'
RETURNING id, tenant_id, email, password_hash, name, role, status, last_login_at, created_at
`

type AcceptInvitationParams struct {
	PasswordHash *string
	ID           uuid.UUID
}

// Only an invited user accepts, so a link stops working once it has been used
// (BR-026).
func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (User, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, slug, timezone, status, created_at, order_prefix FROM tenants WHERE id = $1
`

// tenants has no RLS; the id comes from the caller's own tenant context.
func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.OrderPrefix,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, tenant_id, email, password_hash, name, role, status, last_login_at, created_at FROM users WHERE id = $1
`

// Team: users and the tenant's own settings (P1-064, P1-071, P1-226).
func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const inviteUser = `-- name: InviteUser :one
INSERT INTO users (id, tenant_id, email, name, role, status)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3, $4, 'invited')
RETURNING id, tenant_id, email, password_hash, name, role, status, last_login_at, created_at
`

type InviteUserParams struct {
	ID    uuid.UUID
	Email string
	Name  string
	Role  string
}

func (q *Queries) InviteUser(ctx context.Context, arg InviteUserParams) (User, error) {
	row := q.db.QueryRow(ctx, inviteUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, password_hash, name, role, status, last_login_at, created_at FROM users
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR role = $2::text)
  AND ($3::timestamptz IS NULL
       OR (created_at, id) > ($3::timestamptz, $4::uuid))
ORDER BY created_at, id
LIMIT $5
`

type ListUsersParams struct {
	Status  *string
	Role    *string
	AfterAt *time.Time
	AfterID *uuid.UUID
	Lim     int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Status,
		arg.Role,
		arg.AfterAt,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const otherActiveOwners = `-- name: OtherActiveOwners :one
SELECT count(*)::int FROM users WHERE role = 'owner' AND status = 'active' AND id <> $1
`

// BR-027: the last active owner cannot be demoted or disabled.
func (q *Queries) OtherActiveOwners(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, otherActiveOwners, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users SET role = $1 WHERE id = $2 RETURNING id, tenant_id, email, password_hash, name, role, status, last_login_at, created_at
`

type SetUserRoleParams struct {
	Role string
	ID   uuid.UUID
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.Role, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users SET status = $1 WHERE id = $2 RETURNING id, tenant_id, email, password_hash, name, role, status, last_login_at, created_at
`

type SetUserStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.Status, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}
