// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: variants.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveVariant = `-- name: ArchiveVariant :one
UPDATE variants SET archived_at = coalesce(archived_at, now()), version = version + 1, updated_at = now()
WHERE id = $1
RETURNING id
`

func (q *Queries) ArchiveVariant(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, archiveVariant, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const createVariant = `-- name: CreateVariant :one

INSERT INTO variants (id, tenant_id, product_id, sku, barcode, option_values,
                      regular_price_amount, sale_price_amount, sale_starts_at, sale_ends_at, weight_grams)
VALUES ($1, current_setting('app.tenant_id')::uuid, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10)
RETURNING id
`

type CreateVariantParams struct {
	ID           uuid.UUID
	ProductID    uuid.UUID
	Sku          *string
	Barcode      *string
	OptionValues []string
	RegularPrice int64
	SalePrice    *int64
	SaleStartsAt *time.Time
	SaleEndsAt   *time.Time
	WeightGrams  int32
}

// Variants (P1-029, 04-api-spec.md §7.2). price is variant_price() -- the one
// place a price is decided (BR-046); nothing reads the amounts to charge.
func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ID,
		arg.ProductID,
		arg.Sku,
		arg.Barcode,
		arg.OptionValues,
		arg.RegularPrice,
		arg.SalePrice,
		arg.SaleStartsAt,
		arg.SaleEndsAt,
		arg.WeightGrams,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getVariant = `-- name: GetVariant :one
SELECT v.id, v.tenant_id, v.product_id, v.sku, v.barcode, v.option_values, v.regular_price_amount, v.sale_price_amount, v.sale_starts_at, v.sale_ends_at, v.currency, v.weight_grams, v.archived_at, v.version, v.created_at, v.updated_at, variant_price(v)::bigint AS price FROM variants v WHERE v.id = $1
`

type GetVariantRow struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	ProductID          uuid.UUID
	Sku                *string
	Barcode            *string
	OptionValues       []string
	RegularPriceAmount int64
	SalePriceAmount    *int64
	SaleStartsAt       *time.Time
	SaleEndsAt         *time.Time
	Currency           string
	WeightGrams        int32
	ArchivedAt         *time.Time
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Price              int64
}

func (q *Queries) GetVariant(ctx context.Context, id uuid.UUID) (GetVariantRow, error) {
	row := q.db.QueryRow(ctx, getVariant, id)
	var i GetVariantRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.OptionValues,
		&i.RegularPriceAmount,
		&i.SalePriceAmount,
		&i.SaleStartsAt,
		&i.SaleEndsAt,
		&i.Currency,
		&i.WeightGrams,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Price,
	)
	return i, err
}

const listVariants = `-- name: ListVariants :many
SELECT v.id, v.tenant_id, v.product_id, v.sku, v.barcode, v.option_values, v.regular_price_amount, v.sale_price_amount, v.sale_starts_at, v.sale_ends_at, v.currency, v.weight_grams, v.archived_at, v.version, v.created_at, v.updated_at, variant_price(v)::bigint AS price FROM variants v
WHERE v.product_id = $1 AND (v.archived_at IS NOT NULL) = $2::bool
ORDER BY v.id
`

type ListVariantsParams struct {
	ProductID uuid.UUID
	Archived  bool
}

type ListVariantsRow struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	ProductID          uuid.UUID
	Sku                *string
	Barcode            *string
	OptionValues       []string
	RegularPriceAmount int64
	SalePriceAmount    *int64
	SaleStartsAt       *time.Time
	SaleEndsAt         *time.Time
	Currency           string
	WeightGrams        int32
	ArchivedAt         *time.Time
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Price              int64
}

// Creation order: v7 ids are time-ordered, and the matrix creates rows in grid order.
func (q *Queries) ListVariants(ctx context.Context, arg ListVariantsParams) ([]ListVariantsRow, error) {
	rows, err := q.db.Query(ctx, listVariants, arg.ProductID, arg.Archived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVariantsRow
	for rows.Next() {
		var i ListVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.Sku,
			&i.Barcode,
			&i.OptionValues,
			&i.RegularPriceAmount,
			&i.SalePriceAmount,
			&i.SaleStartsAt,
			&i.SaleEndsAt,
			&i.Currency,
			&i.WeightGrams,
			&i.ArchivedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sKUHolder = `-- name: SKUHolder :one
SELECT v.id, p.title FROM variants v JOIN products p ON p.id = v.product_id WHERE v.sku = $1::text
`

type SKUHolderRow struct {
	ID    uuid.UUID
	Title string
}

// The variant and product that already hold a SKU, for the duplicate_sku
// message (BR-039).
func (q *Queries) SKUHolder(ctx context.Context, sku string) (SKUHolderRow, error) {
	row := q.db.QueryRow(ctx, sKUHolder, sku)
	var i SKUHolderRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE variants SET
  sku                  = CASE WHEN $1::bool THEN $2 ELSE sku END,
  barcode              = CASE WHEN $3::bool THEN $4 ELSE barcode END,
  regular_price_amount = coalesce($5, regular_price_amount),
  sale_price_amount    = CASE WHEN $6::bool THEN $7 ELSE sale_price_amount END,
  sale_starts_at       = CASE WHEN $8::bool THEN $9 ELSE sale_starts_at END,
  sale_ends_at         = CASE WHEN $10::bool THEN $11 ELSE sale_ends_at END,
  weight_grams         = coalesce($12, weight_grams),
  version              = version + 1,
  updated_at           = now()
WHERE id = $13 AND version = $14
RETURNING id
`

type UpdateVariantParams struct {
	SetSku        bool
	Sku           *string
	SetBarcode    bool
	Barcode       *string
	RegularPrice  *int64
	SetSalePrice  bool
	SalePrice     *int64
	SetSaleStarts bool
	SaleStartsAt  *time.Time
	SetSaleEnds   bool
	SaleEndsAt    *time.Time
	WeightGrams   *int32
	ID            uuid.UUID
	Version       int32
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.SetSku,
		arg.Sku,
		arg.SetBarcode,
		arg.Barcode,
		arg.RegularPrice,
		arg.SetSalePrice,
		arg.SalePrice,
		arg.SetSaleStarts,
		arg.SaleStartsAt,
		arg.SetSaleEnds,
		arg.SaleEndsAt,
		arg.WeightGrams,
		arg.ID,
		arg.Version,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
